echo "
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasrch-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasrch-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/hostpath-provisioner/kong/data-elasticsearch"
" | kubectl apply -f - -n kong
