apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasrch-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/hostpath-provisioner/kong/data-elasticsearch"