echo "
kind: Deployment
apiVersion: apps/v1
metadata:
  name: log-manual
spec:
  replicas: 1
  selector:
    matchLabels:
      name: log-manual
  template:
    metadata:
      labels:
        name: log-manual
    spec:
      containers:
      - name: log-manual
        image: logstash:7.8.0
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: log-manual-pipeline
          mountPath: /usr/share/logstash/pipeline/
        command:
        - logstash
      volumes:
      - name: log-manual-pipeline
        configMap:
          name: log-manual-pipeline 
          items:
          - key: logstash.conf
            path: logstash.conf
" | kubectl apply -f - -n kong